"""China A-Share Market Microstructure Hard Rules & Prompt Constraints.

Encodes institutional rules of China A-share equity trading into:
1. Standard Market Microstructure Rule Specifications (T+1, Long-Only, Price Limits, Tax/Fees).
2. LLM / Co-STEER Prompt Constraint Injector for Strategy Synthesis.
3. Static & Dynamic Runtime Rule Validator for Signals and Trade Sequences.
"""

from __future__ import annotations

from collections.abc import Sequence
from dataclasses import dataclass, field
from datetime import date, datetime
from decimal import Decimal
from typing import Any


@dataclass(frozen=True)
class AShareMarketRules:
    """Institutional microstructure specifications for China A-Share markets."""

    t_plus_1_settlement: bool = True
    long_only_spot: bool = True
    allow_naked_short: bool = False

    # Price Limits (Daily limit up / limit down)
    price_limit_main_board: float = 0.10  # 00xxxx, 60xxxx (+/-10%)
    price_limit_chinext_star: float = 0.20  # 30xxxx, 68xxxx (+/-20%)
    price_limit_st: float = 0.05  # ST / *ST (+/-5%)
    price_limit_first_day: float = 0.00  # First day of IPO: unconstrained or special

    # Transaction Friction Costs
    stamp_duty_sell_only: float = 0.0005  # 0.05% (5‱) imposed on seller only
    transfer_fee_both_sides: float = 0.00001  # 0.01‰ (0.1‱) China Clear both sides
    handling_fee_both_sides: float = 0.0000341  # Exchange handling & regulation fee
    broker_commission_rate: float = 0.00025  # Standard万2.5
    broker_commission_min_cny: float = 5.0  # Minimum 5 CNY per trade
    standard_slippage_bps: float = 1.5  # 1.5 bps standard liquidity slippage


class ASharePromptContext:
    """Formats and injects A-Share microstructure constraints into LLM / Co-STEER prompts."""

    @classmethod
    def render_prompt_constraints(cls, *, include_costs: bool = True) -> str:
        """Render markdown text block of mandatory A-Share trading constraints."""
        lines = [
            "### 【强制执行】中国 A 股市场微观结构与制度硬约束 (China A-Share Hard Rules)",
            "1. **T+1 交易交收与可用仓位约束 (T+1 Settlement)**:",
            (
                "   - 当日（T 日）买入的股票必须在 T+1 交易日方可卖出，"
                "严禁在同一交易日内对同一标的反复平开仓;"
            ),
            (
                "   - 策略必须区分【总持仓】与【T+1 可用持仓】，"
                "日内止损逻辑不能假设当天开仓后能立刻平仓出场。"
            ),
            "2. **现货单向多头限制 (Long-Only Spot - 禁止裸做空)**:",
            (
                "   - 现货股票账户严禁裸卖空。交易信号值严格限定为："
                "`1`（做多买入）或 `0`（清仓观望/卖出平仓）；"
            ),
            (
                "   - 严禁产生 `-1` 的开空信号，`position_sizing` 仓位区间必须"
                "严格处于 `[0.0, 1.0]`，严禁负持仓。"
            ),
            "3. **涨跌停板与流动性截断 (Price Limit & Truncation)**:",
            (
                "   - 主板（60/00）涨跌幅限制为 ±10%，创业板（30）及科创板（68）"
                "限制为 ±20%，ST 股为 ±5%；"
            ),
            (
                "   - 封死涨停板时无法买入成交，封死跌停板时无法卖出止损。"
                "严禁利用封板极端价制造'假成交'。"
            ),
        ]
        if include_costs:
            lines.extend(
                [
                    "4. **交易摩擦与法定税费模型 (Friction Costs & Stamp Duty)**:",
                    "   - 印花税：仅出让方（卖出）单边征收 0.05%（万分之 5）；",
                    "   - 过户费与经手费：买卖双边合计约万分之 0.44；",
                    "   - 券商佣金：买卖双向标准按万分之 2.5 计，单笔不足 5 元按 5 元计；",
                    "   - 执行滑点：保守估计预留 1.5 ~ 2.0 bps 滑点，过滤无摩擦虚假 Alpha。",
                ]
            )
        return "\n".join(lines)


@dataclass
class AShareValidationReport:
    """Report generated by AShareRuleValidator."""

    valid: bool
    violations: list[str] = field(default_factory=list)
    warnings: list[str] = field(default_factory=list)
    metrics: dict[str, Any] = field(default_factory=dict)


class AShareRuleValidator:
    """Validates signal arrays, positions and trade timelines against A-Share rules."""

    @classmethod
    def validate_signals_and_positions(
        cls,
        signals: Sequence[int | float],
        positions: Sequence[float | Decimal] | None = None,
    ) -> AShareValidationReport:
        """Validate that signals and positions satisfy the Long-Only spot rule."""
        violations: list[str] = []
        warnings: list[str] = []

        # Check signals
        for idx, sig in enumerate(signals):
            if sig < 0:
                violations.append(
                    f"A-Share Long-Only Violation: Signal at index {idx} has negative value {sig}. "
                    "Short selling (-1) is prohibited in China spot equities."
                )

        # Check positions
        if positions is not None:
            for idx, pos in enumerate(positions):
                pos_val = float(pos)
                if pos_val < 0.0:
                    violations.append(
                        f"A-Share Spot Violation: Position sizing at index {idx} "
                        f"is negative ({pos_val}). "
                        "Negative positions are illegal for spot accounts."
                    )
                elif pos_val > 1.0:
                    warnings.append(
                        f"Position sizing at index {idx} exceeds 1.0 ({pos_val}); "
                        "leverage is not permitted for standard spot trading."
                    )

        return AShareValidationReport(
            valid=len(violations) == 0,
            violations=violations,
            warnings=warnings,
            metrics={"total_bars": len(signals), "violation_count": len(violations)},
        )

    @classmethod
    def validate_t1_sequence(
        cls,
        timestamps: Sequence[datetime | date | str | int],
        signals: Sequence[int | float],
        *,
        signal_mode: str = "position",
    ) -> AShareValidationReport:
        """Validate T+1 compliance ensuring intraday buy-then-sell is not executed.

        Args:
            timestamps: Bar timestamps.
            signals: Signal sequence. If signal_mode="position", 1 indicates long and
                0 indicates flat (sell occurs only on 1 -> 0 transition).
                If signal_mode="action", 1 is buy, -1 is sell, and 0 is hold.
            signal_mode: "position" or "action".
        """
        if len(timestamps) != len(signals):
            return AShareValidationReport(
                valid=False,
                violations=["timestamps and signals length mismatch"],
            )

        violations: list[str] = []
        dates: list[date] = []
        for ts in timestamps:
            if isinstance(ts, datetime):
                dates.append(ts.date())
            elif isinstance(ts, date):
                dates.append(ts)
            elif isinstance(ts, str):
                try:
                    dt = datetime.fromisoformat(ts.replace("Z", "+00:00"))
                    dates.append(dt.date())
                except Exception:
                    dates.append(date.fromisoformat(ts[:10]))
            elif isinstance(ts, (int, float)):
                sec = ts / 1000.0 if ts > 1e11 else float(ts)
                dates.append(datetime.fromtimestamp(sec).date())
            else:
                violations.append(f"unsupported timestamp type: {type(ts)}")
                return AShareValidationReport(valid=False, violations=violations)

        available_shares = 0
        pending_shares = 0
        current_day: date | None = None
        prev_sig: float = 0.0

        for idx, (d, sig_raw) in enumerate(zip(dates, signals, strict=False)):
            sig = float(sig_raw)
            if current_day != d:
                # Settle yesterday's buys
                available_shares += pending_shares
                pending_shares = 0
                current_day = d

            is_buy = False
            is_sell = False

            if signal_mode == "position":
                if sig > 0 and prev_sig <= 0:
                    is_buy = True
                elif sig <= 0 and prev_sig > 0:
                    is_sell = True
            else:  # action mode
                if sig > 0:
                    is_buy = True
                elif sig < 0:
                    is_sell = True

            if is_buy:
                pending_shares += 1
            elif is_sell:
                if available_shares <= 0 and pending_shares > 0:
                    violations.append(
                        f"T+1 Settlement Violation at bar {idx} (date {d}): "
                        "Attempted to sell shares on the same day they were bought. "
                        "Available T+1 shares = 0."
                    )
                elif available_shares > 0:
                    available_shares -= 1

            prev_sig = sig

        return AShareValidationReport(
            valid=len(violations) == 0,
            violations=violations,
            metrics={"trade_days": len(set(dates)), "violation_count": len(violations)},
        )

    @classmethod
    def calculate_friction_costs(
        cls,
        *,
        buy_turnover: float,
        sell_turnover: float,
        slippage_bps: float = 1.5,
    ) -> dict[str, float]:
        """Compute complete institutional A-Share transaction friction breakdown in CNY."""
        rules = AShareMarketRules()

        # 1. Stamp Duty (印花税, 0.05% sell only)
        stamp_duty = sell_turnover * rules.stamp_duty_sell_only

        # 2. Transfer Fee (过户费, 0.001% both sides)
        transfer_fee = (buy_turnover + sell_turnover) * rules.transfer_fee_both_sides

        # 3. Handling Fee (经手费与证管费, ~0.00341% both sides)
        handling_fee = (buy_turnover + sell_turnover) * rules.handling_fee_both_sides

        # 4. Broker Commission (万2.5, min 5 CNY per side if non-zero)
        buy_comm = (
            max(rules.broker_commission_min_cny, buy_turnover * rules.broker_commission_rate)
            if buy_turnover > 0
            else 0.0
        )
        sell_comm = (
            max(rules.broker_commission_min_cny, sell_turnover * rules.broker_commission_rate)
            if sell_turnover > 0
            else 0.0
        )
        commission = buy_comm + sell_comm

        # 5. Slippage (e.g. 1.5 bps)
        slippage_rate = slippage_bps / 10000.0
        slippage_cost = (buy_turnover + sell_turnover) * slippage_rate

        total_friction = stamp_duty + transfer_fee + handling_fee + commission + slippage_cost

        return {
            "stamp_duty": round(stamp_duty, 2),
            "transfer_fee": round(transfer_fee, 2),
            "handling_fee": round(handling_fee, 2),
            "commission": round(commission, 2),
            "slippage_cost": round(slippage_cost, 2),
            "total_friction": round(total_friction, 2),
            "effective_friction_bps": (
                round((total_friction / (buy_turnover + sell_turnover)) * 10000.0, 2)
                if (buy_turnover + sell_turnover) > 0
                else 0.0
            ),
        }
